---

- name: Create redis group
  group: name={{ redis_group }} gid={{ redis_gid }} state=present

- name: Create redis user
  user:
    name: "{{ redis_user }}"
    uid: "{{ redis_uid }}"
    group: "{{ redis_group }}"
    shell: /bin/bash
    state: present

- name: Unarchive redis
  unarchive:
    src: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
    dest: '{{ redis_build_dir }}'
    copy: no
    creates: "{{ redis_build_dir }}/redis-{{ redis_version}}"

- name: Build redis
  shell: cd {{ redis_build_dir }}/redis-{{ redis_version}} && make distclean && make

- name: Install TCL for testing redis
  yum:
    name: tcl
    state: present

# - name: Test redis
#   shell: cd {{ redis_build_dir }}/redis-{{ redis_version|default('3.2.6')}} && make test

- name: Install redis
  shell: cd {{ redis_build_dir }}/redis-{{ redis_version}} && make PREFIX={{ redis_home }} install

- name: Create redis conf directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '{{ redis_conf_dir }}'
    - '{{ redis_run_dir }}'

- name: Create redis data directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ redis_user }}'
    group: '{{ redis_group }}'
    mode: 0755
  with_items:
    - '{{ redis_data_dir }}'
    - '{{ redis_log_dir }}'

- name: Configure redis
  template:
    src: redis.conf.j2
    dest: '{{ redis_conf_dir }}/redis_{{ redis_port }}'
    mode: 0644