---

- name: Create redis group
  group: name={{ redis_group }} gid={{ redis_gid }} state=present

- name: Create redis user
  user:
    name: "{{ redis_user }}"
    uid: "{{ redis_uid }}"
    group: "{{ redis_group }}"
    shell: /bin/bash
    state: present

- name: Check redis
  stat:
    path: "{{ redis_home }}/bin/redis-server"
  register: redis

- name: Unarchive redis
  get_url:
    src: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
    dest: "{{ redis_cache_dir }}/redis-{{ redis_version }}.tar.gz"
    creates: "{{ redis_cache_dir }}/redis-{{ redis_version }}.tar.gz"
  when: redis.stat.exists == False

- name: Unarchive redis
  unarchive:
    src: "{{ redis_cache_dir }}/redis-{{ redis_version }}.tar.gz"
    dest: "{{ redis_cache_dir }}"
    copy: no
    creates: "{{ redis_cache_dir }}/redis-{{ redis_version}}"
  when: redis.stat.exists == False

- name: Build redis
  shell: make distclean && make
  args:
    chdir: "{{ redis_cache_dir }}/redis-{{ redis_version}}"
  when: redis.stat.exists == False

- name: Install TCL for testing redis
  yum:
    name: tcl
    state: present

# - name: Test redis
#   shell: cd {{ redis_cache_dir }}/redis-{{ redis_version|default('3.2.6')}} && make test

- name: Install redis
  shell: cd {{ redis_cache_dir }}/redis-{{ redis_version}} && make PREFIX={{ redis_home }} install
  when: redis.stat.exists == False

- name: Create redis conf directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '{{ redis_conf_dir }}'

- name: Create redis data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
  with_items:
    - '{{ redis_data_dir }}'
    - '{{ redis_log_dir }}'
    - '{{ redis_run_dir }}'

- name: Configure redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_dir }}/redis_{{ redis_port }}.conf"
    mode: 0644

- name: Create redis startup script
  template:
    src: centos/etc_init.d_redis.j2
    dest: /etc/init.d/redis_{{ redis_port }}
    mode: 0755

- name: Enable redis service
  service:
    name: redis_{{ redis_port }}
    enabled: yes