---

- name: Install build-essential Ubuntu
  include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install build-essential CentOS
  include: redhat.yml
  when: ansible_distribution == "CentOS"