---

- name: Copy repo file - RedHat based distro
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Authenticate nginx repository - RedHat based distro
  rpm_key:
    key: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Update package manager - RedHat based distro
  shell: yum update